import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";
import ThemeToggleProvider from "@/lib/ThemeToggleProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yariga Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-lightBg dark:bg-darkBg">
        <ThemeToggleProvider>
          <main>{children}</main>
        </ThemeToggleProvider>
      </body>
    </html>
  );
}
